apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ k8s_namespace }}"
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      rewrite ^(.*)$ https://lk.dataschool.yandex.ru$1 permanent;
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      {% for domain in domains -%}
      - {{ domain }}
      {% endfor %}
      secretName: "letsencrypt-{{ k8s_namespace }}"
  rules:
  {% for domain in domains -%}
  - host: {{ domain }}
    http:
      paths:
        - path: /static/
          backend:
            serviceName: "{{ backend_service_name }}-backend"
            servicePort: {{ backend_nginx_service_port }}
        - path: /
          backend:
            serviceName: "{{ backend_service_name }}-backend"
            servicePort: {{ backend_django_service_port }}
  {% endfor %}
